### ISSUE TITLE
ESPUI.updateSwitcher

### ISSUE THREAD

**Issue by Rumen33** [s00500/ESPUI#121]
The problem appears if you have a switch with UI control and also with a local control by a physical button connected to the ESP input pin. Both controls (from the UI and from the local button) are working properly. When changing the output state by the physical button, I'm using the ESPUI.updateSwitcher to update the UI element. The UI element is properly updating its position, but the next pressing on the UI switch is sending the same value. You need to press again in order to change the output state. For example:
- The initial status of the channel is Off.
- pressing the physical button is changing the output state to On
`
MessageEvent {isTrusted: true, data: "{"type":105,"value":"1","id":5,"color":3}", origin: "ws://192.168.0.120", lastEventId: "", source: null, …}
`
- ESPUI.updateSwitcher is changing the UI element to On
- Clicking on the UI  switch is sending the same (value: 1) and not changing the output state
`MessageEvent {isTrusted: true, data: "{"type":105,"value":"1","id":5,"color":3}", origin: "ws://192.168.0.120", lastEventId: "", source: null, …}`
- Second click on the UI switch is already sending value: 0, and the output is switching Off:
`MessageEvent {isTrusted: true, data: "{"type":105,"value":"0","id":5,"color":3}", origin: "ws://192.168.0.120", lastEventId: "", source: null, …}`

I suppose the problem is in controls.js - the switch is always sending a value opposite to the last sent one, even in case it was already updated to another state by means of ESPUI.updateSwitcher(). 

Any advice, how to edit the script in order to solve the problem?

**Comment by Rumen33** [comment]
Some support here? Just any advice regarding control.js?

**Comment by DenverClarke** [comment]
I also experienced this issue with switchers that affects other switchers.

**Comment by s00500** [comment]
Please test the branch fix_switcher and let me know if it fixes the issue

**Comment by thomastech** [comment]
I have the Switch Control sync problem with the latest build (released a couple days ago). The fix_switcher branch is now too far behind to test with my project. So I tried to do a manual patch. 

Since I'm using LITTLEFS I only updated the two lines in data/js/controls.js and one line in src/dataControlsJS.h (skipped the gzip data). That didn't work. Digging deeper I suspect it's because of dataControlsJS.h needs to be compiled.

So put me down as a volunteer to test this out. I just need a kind soul to apply the patch to the current code base. 

- Thomas

**Comment by iangray001** [comment]
Hi Thomas, your message caught me in the middle of hacking. 

That `fix_switcher` branch isn't going to fix the problem, but I've debugged what is going on and corrected the mistake. I am currently working on another issue and am preparing a branch and PR over on my dev fork, but I've corrected this bug in my branch so you can test two things at the same time for me ;)

Can you pull and try this branch please: https://github.com/iangray001/ESPUI/tree/chunkupdates2

**Comment by thomastech** [comment]
Hello Ian,

Fast service! Thanks for looking at this.

I tested the revised Switcher and I'm still experiencing the problem. That is to say, if I use updateControlValue() to change the Switcher to the opposite state, it is out-of-sync on the next use. But OK on the second switch operation. Until the next programmable state change.

- Thomas

**Comment by iangray001** [comment]
Interesting. So I'm doing this to toggle a switch and it seems to be fine:

```
ESPUI.updateSwitcher(mainSwitcher, ESPUI.getControl(mainSwitcher)->value.toInt() ? false : true);
```

Just to double check, you're sending strings to `updateControlValue`? i.e. `"1"` and `"0"` not `1` or `true` or anything?

**Comment by thomastech** [comment]
A thousand pardons, it works great!

I had the project open when I updated the ESPUI library. So Platformio cheerfully overwrote some files, essentially pushing me back to the old version. Reinstalled library and was rewarded with working Switchers.

Thanks again for solving another quirk.

- Thomas

**Comment by iangray001** [comment]
Brill, well by doing this you are also testing a much more significant under-the-hood update in the UI transport layer. It should now not be possible to overflow any buffers no matter how big the UI gets.

**Comment by thomastech** [comment]
`It should now not be possible to overflow any buffers no matter how big the UI gets.`

Brilliant. Sounds like you're challenging me to break it. :)

I did some rapid button presses and the serial log spilled out several "ERROR: Too many messages queued". Is your update suppose to prevent those?

- Thomas

**Comment by iangray001** [comment]
No. I have seen that error is an open issue, but I've not turned my radar to looking at that one yet.

It's on the list ;)

**Comment by thomastech** [comment]
Good luck hunting the code demons. For the next few days I should have some free time for testing, so just ping me if you need assistance with that.

- Thomas
