### ISSUE TITLE
Crash on page load

### ISSUE THREAD

**Issue by mano1979** [s00500/ESPUI#6]
On a generic ESP32-dev board:

Uploaded the filesystem with the sketch. first time i didn't do a reset. I just let it run after upload. Not every file was written so i got the "Control Offline" message.
2nd upload and a reset after the upload fixed this. 

But now when i load the page, i get nothing and the esp32 reboots. serial output below:

```ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:812
load:0x40078000,len:0
load:0x40078000,len:11392
entry 0x40078a9c

IP address: 192.168.4.1
UI Initialized
CORRUPT HEAP: Bad tail at 0x3ffdf74a. Expected 0xbaad5678 got 0xbaad5600
assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/./multi_heap_poisoning.c", line 199, function: multi_heap_free
abort() was called at PC 0x400dea73 on core 1

Backtrace: 0x40087ca8:0x3ffdd720 0x40087da7:0x3ffdd740 0x400dea73:0x3ffdd760 0x400879b9:0x3ffdd790 0x40083b76:0x3ffdd7b0 0x400840f9:0x3ffdd7d0 0x4000bec7:0x3ffdd7f0 0x400da09f:0x3ffdd810 0x400d8dda:0x3ffdd860 0x400d80d9:0x3ffdd8a0 0x400d6f08:0x3ffdd8e0 0x400d898b:0x3ffdd950 0x400d89f9:0x3ffdd990 0x400d8c0d:0x3ffdd9e0 0x400d4a66:0x3ffdda00 0x400d4c4d:0x3ffdda50

Rebooting...```

**Comment by s00500** [comment]
hey, sry for the late response, what version of the espasyncwebserver library are you using? I am going to test this in the next days again

**Comment by mano1979** [comment]
That has to be the latest version. I downloaded it all 2 days ago.

**Comment by s00500** [comment]
OK then, this issue drove me crazy today.... The problem is that the prepareFilesystem function does write the files correct, and if I list the filesystem contents immediatly afterwards it looks all fine

But when I list the contents in a new sketch it only shows some of them.... and if the webserver can not find them it crashes

This stops once I remove all file exists and remove operations in the function. I am not sure why this is but for now I'll leave it like this, if anyone has an Idea why the FS on the ESP32 behaves so strange please let me know

I released a new patch version with the delete parts commented out

**Comment by mano1979** [comment]
I tested the patch, but i still get the "Control Offline" page.

**Comment by s00500** [comment]
This is an annoying problem, I have to do more checks but for now pls use the ESP32 Sketch Data upload tool

As you can see in your debug output there is always one file with a size of 0, in this case /js/controls.js...
This somehow causes the server to crash...

**Comment by mano1979** [comment]
indeed. uploading using the sketch data upload tool worked.

**Comment by mano1979** [comment]
Do you happen to know if it is possible to give the sliders "touch" support?
Now you have to tap somewhere on the line, hoping you land in the right spot.
If the sliders where drag-able, then we can see the number according to position.

Any help or clues on where to start are appreciated. :)

**Comment by s00500** [comment]
Hm, that actually should already work... If it doesn't: can you put it into a new issue and put in info about the device you are using?

**Comment by cmorrow101** [comment]
I wanted to share an observation. I see the same reset problem when connecting through chrome web browser, however when I setup a hotspot on my phone, then connect to the ESP32(using the same phone) and mobile chrome, all works perfectly. 
What is the difference when connecting directly vs through a network router?
Hopefully this is another clue. Great work BTW, love the interface.

**Comment by s00500** [comment]
This is probably some caching related issue you are having there, anyway the main problem is that the files are not written to the filesystem properly using prepareFilesystem() ...

**Comment by s00500** [comment]
Alright everyone: Great News: I retested on ESP32 and on ESP8266 and both are working fine with the newest versions of the arduino cores, this means this issue can be closed now =D
